version: '3.8'

networks:
  playlist:
    driver: bridge

services:
  backend:
    build: ./backend
    volumes:
      - ${MUSIC_PATH}:/music:ro
      - ./data:/data:rw
    restart: unless-stopped
    networks:
      - playlist
    expose:
      - 3000
    environment:
      - LASTFM_API_KEY="b71f009e60523e1c055eb8e1b9b6a854"
      - LASTFM_SHARED_SECRET="6c9c65258db4340d30f35928e5a2c5dc"
      - MUSIC_PATH=/music

  frontend:
    build: ./frontend
    ports:
      - "5173:8080"
    volumes:
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
    restart: unless-stopped
    networks:
      - playlist
